### ISSUE TITLE
Recieved json lacks support of detailed fileds

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/oec#4]
Hi. 
I am trying to integrate oec with my system. 
Json allert from opsgenie looks much better than in marid but i don't have details filed aka extraproperties. 
I want to add that fields to my system

**Comment by metehanozturk** [comment]
Extra properties are not supported now but it will be evaluated to add it. Thank you for your feedback!

**Comment by freeseacher** [comment]
as far as i can see that filed have to be send to achieve nagios integration to work 
https://github.com/opsgenie/oec-scripts/blob/master/Nagios/nagiosActionExecutor.py#L38

**Comment by metehanozturk** [comment]
That's true. Due to the new approach of the Opsgenie integrations, extra properties (aka details) is not used to avoid redundancy. But the integrations that follow the old approach (like Nagios, Solarwinds, Zabbix, etc.) still contain this field. So it is still usable in Nagios script.

**Comment by freeseacher** [comment]
what kind of redundancy ?
as far as i can see the only field i can use as key value is details. 
That field can be send from prometheus integration as consistent data that should not be parsed than anyhow.

**Comment by metehanozturk** [comment]
Nagios payload already has "details" field because of being the old one. In your case, you won't be affected i guess. Other integrations did not need those extra properties in use-cases until now and those are truncated to decreases the size of the json for simply avoiding network issues. 
As I said, we will evaluate the issue of providing more support for custom fields.
