### ISSUE TITLE
Multiple tasks on one actionMapping

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/oec#6]
Hi. 
i am wondering how can i run multiple jobs on one action.
My flow expected to be like 
On close:
  * if alert lasts more than 10 minutes -> create jira task. else nothing (i can handle it in one script)
  * Create slack channel and gather people to it.

**Comment by metehanozturk** [comment]
Multiple jobs for one action is not supported, one-to-one mapping is presented. You can handle all the jobs in one script with the help of OEC integration or you can create two different integration and run two OEC for different jobs. If there are numerous separated flows, the second case seems more appropriate way instead of mixing all the jobs related with different tools. Actually, there are already different integrations to handle different jobs for this purpose. Scripts are prepared for different integrations. 

By the way, while OEC integration uses directly actual actions (e.g. "Create", "Close", "Acknowledge", etc.), other integrations will use primarily "mappedAction" related with themselves (e.g. "addCommentToIssue", "createIssue", etc. for Jira integration). I said "will" because the last version is not released yet. I guess you are using v1.0.0 and to try mapped actions, you can clone, build and run.

**Comment by metehanozturk** [comment]
New OEC packages that cover the case I explained above will probably be released today. Don't bother with cloning the last version.

**Comment by metehanozturk** [comment]
1.0.1.beta version is released and example config files that you can investigate defined mapped actions for each integration are added to oec-scripts repo. You can download new packages from the link:
 https://docs.opsgenie.com/docs/oec-installation
